CREATE USER testUser;

DROP DATABASE IF EXISTS app_dev;  
DROP DATABASE IF EXISTS app_test;  

CREATE DATABASE app_dev;
CREATE DATABASE app_test;

GRANT ALL PRIVILEGES ON DATABASE app_dev TO testUser;
GRANT ALL PRIVILEGES ON DATABASE app_test TO testUser;
